In [5]:
from caffe2.python import workspace,core
import numpy as npimport pandas as pd

In [6]:
print(workspace.CurrentWorkspace())

newWorkspace2


In [7]:
workspace.SwitchWorkspace('newWorkspace2', True)

In [8]:
print(workspace.CurrentWorkspace())

newWorkspace2


In [9]:
blob_x = np.random.rand(3,2).astype(np.float64)

In [10]:
blob_x

array([[0.08033955, 0.44323464],
       [0.45641212, 0.42106656],
       [0.89336195, 0.82107712]])

In [11]:
print(blob_x)

[[0.08033955 0.44323464]
 [0.45641212 0.42106656]
 [0.89336195 0.82107712]]


In [14]:
workspace.FeedBlob('blob_x',blob_x)

True

In [15]:
print('Blobs in this workspace:',workspace.Blobs())

Blobs in this workspace: ['blob_x']


In [16]:
print('Workspace has blob_y:',workspace.HasBlob('blob_y'))

Workspace has blob_y: False


In [17]:
print('Workspace has blob_x:',workspace.HasBlob('blob_x'))

Workspace has blob_x: True


In [18]:
print('Fetch data from specific blob::',workspace.FetchBlob('blob_x'))

Fetch data from specific blob:: [[0.08033955 0.44323464]
 [0.45641212 0.42106656]
 [0.89336195 0.82107712]]


In [19]:
# there is no error, so the blobs are the same!
np.testing.assert_array_equal(blob_x,workspace.FetchBlob('blob_x'))

In [20]:
workspace.ResetWorkspace()

True

In [21]:
oper_resize = core.CreateOperator(
    'ResizeLike',
    ['blob_x','blob_y'],
    ['blob_out'],
)

In [22]:
oper_resize

input: "blob_x"
input: "blob_y"
output: "blob_out"
name: ""
type: "ResizeLike"

In [23]:
type(oper_resize)

caffe2.proto.caffe2_pb2.OperatorDef

In [24]:
workspace.ResetWorkspace()

True

In [26]:
blob_y = np.random.rand(6)

In [27]:
blob_y

array([0.41924126, 0.09575767, 0.61508351, 0.95281205, 0.06750945,
       0.07391797])

In [28]:
blob_x

array([[0.08033955, 0.44323464],
       [0.45641212, 0.42106656],
       [0.89336195, 0.82107712]])

In [29]:
workspace.FeedBlob('blob_x', blob_x)
workspace.FeedBlob('blob_y', blob_y)

True

In [32]:
print(workspace.HasBlob('blob_y'))
print(workspace.HasBlob('blob_y'))

True
True


In [34]:
workspace.Blobs()

['blob_x', 'blob_y']

In [38]:
type(workspace.FetchBlob('blob_y'))

numpy.ndarray

In [39]:
workspace.RunOperatorOnce(oper_resize)

True

In [42]:
workspace.Blobs()

['blob_out', 'blob_x', 'blob_y']

In [43]:
workspace.FetchBlob('blob_out')

array([0.08033955, 0.44323464, 0.45641212, 0.42106656, 0.89336195,
       0.82107712])